# Generated by Django 5.2.14 on 2026-05-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OSINT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_username', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('img', models.URLField(blank=True)),
                ('contact', models.URLField(blank=True)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SearchQuery',
        ),
    ]
