# Generated by Django 5.2.14 on 2026-05-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OSINT', '0002_telegramsearch_delete_searchquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_username', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('followers', models.TextField(blank=True)),
                ('following', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('organization', models.TextField(blank=True)),
                ('repositories', models.IntegerField(blank=True)),
                ('avatar', models.URLField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
