# Generated by Django 5.2.14 on 2026-05-12 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OSINT', '0003_githubsearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubsearch',
            old_name='username',
            new_name='fullname',
        ),
    ]
