# Generated by Django 5.2.14 on 2026-05-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OSINT', '0004_rename_username_githubsearch_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubsearch',
            name='followers',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='githubsearch',
            name='following',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='githubsearch',
            name='organization',
            field=models.IntegerField(blank=True),
        ),
    ]
