# Generated by Django 5.2.14 on 2026-05-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OSINT', '0005_alter_githubsearch_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubsearch',
            name='organization',
            field=models.CharField(blank=True),
        ),
    ]
