# Generated by Django 5.2.14 on 2026-05-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OSINT', '0006_alter_githubsearch_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramsearch',
            name='description',
            field=models.CharField(blank=True),
        ),
    ]
