# Generated by Django 5.2.14 on 2026-05-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OSINT', '0007_alter_telegramsearch_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramsearch',
            name='contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramsearch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramsearch',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramsearch',
            name='searched_username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='telegramsearch',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
