# Generated by Django 5.2.14 on 2026-05-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OSINT', '0008_alter_telegramsearch_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubsearch',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='githubsearch',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='githubsearch',
            name='followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='githubsearch',
            name='following',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='githubsearch',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='githubsearch',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='githubsearch',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='githubsearch',
            name='organization',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='githubsearch',
            name='repositories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='githubsearch',
            name='searched_username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
